### Register a new Klienta
POST http://localhost:8080/clients/add
Content-Type: application/json

{
  "idKlienta": null,
  "imie": "Fufix",
  "nazwisko": "Gnufix",
  "nrTelefonu": "777777777",
  "plec": "M",
  "idSalonu": 1,
  "idAdresu": 5
}

### Rate an Usluger
POST http://localhost:8080/clients/rateusluger/1
Content-Type: application/json

{
  "idOceny": null,
  "wysokosc": 5,
  "tresc": "Review bombing!",
  "idPracownika": 2,
  "idKlienta": 1
}