### Wylistuj wszystkich pracowników
GET http://localhost:8080/admin/pracownicy/list

### Zatrudnij nowego pracownika
POST http://localhost:8080/admin/pracownicy/add
Content-Type: application/json

{
  "imie": "Jan",
  "nazwisko": "Kowalski",
  "pesel": "12345678901",
  "miasto": "Warszawa",
  "ulica": "Srebrna",
  "kodPocztowy": "00-001",
  "nrBudynku": 10,
  "nrLokalu": 5,
  "stanowisko": "usluger",
  "trybPracy": "pol etatu",
  "pensja": 7500.50
}


### Zwolnij pracownika
PUT http://localhost:8080/admin/pracownicy/delete
Content-Type: application/json

29

### Zmien model pracownika
PUT http://localhost:8080/admin/pracownicy/update_model
Content-Type: application/json

{
  "idPracownika": 48,
  "stanowisko": "sprzedawca",
  "trybPracy": "cwierc etatu",
  "pensja": 1000.5
}

### Dodaj model pracy
POST http://localhost:8080/admin/pracownicy/add_model
Content-Type: application/json

{
  "idModelu": null,
  "stanowisko": "usluger",
  "pensja": 10000,
  "trybPracy": "pelny etat"
}
